
services:
  mysqldatabase:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=u_information
    container_name: "mysqldatabase"
    networks:
      - my-network
    healthcheck:
      test: ['CMD','mysqladmin','ping','-h','localhost']
      timeout: 20s
      retries: 10

  mysqlapp:
    build: ./
    container_name: mysqlapp
    networks:
      - my-network
    volumes:
      - ./servers.txt:/sql/servers.txt
    depends_on:
      mysqldatabase:
        condition: service_healthy
    stdin_open: true
    tty: true

networks:
  my-network:




